version: '3'

services:
  facets-api:
    image : off-facets-knowledge-panels-api:${VERSION:-dev}
    ports:
      - "${API_EXPOSE}:80"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]