#----------------------------------------------
# Generate and upload documentation (only push to main)
#----------------------------------------------

name: Generate documentation
on:
  pull_request:
    # on pull request we just want to build to see nothing is broken
    paths:
    - "README.md"
    - "docs/**"
    - ".github/workflows/generate-docs.yml"
    - "mkdocs.yml"
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
      - name: Deploy 🚀
        # we only deploy on push to main
        if: |
          github.event_name == 'push' && github.event.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: gh_pages # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
